### ISSUE TITLE
add_actor api does not send source parameter to crits

### ISSUE THREAD

**Issue by sabade** [crits/pycrits#7]
the add_actor api does not pass the value of source to crits resulting in a return of
{u'message': u'Missing source information.', u'type': u'Actor', u'return_code': 1, u'id': u''}

changing the code to
    def add_actor(self, name, source, params={}):
        params['name'] = name
        params['source'] = source  # Fix to send the source in for creating an actor
        return self._post(self._ACTORS, params)

fixes this

I would create a pull request, however i don't appear to have access to this project

**Comment by wxsBSD** [comment]
Fixed! Also, not sure what you mean about not having access. You should be able to fork it, commit your fix on a branch in your fork and then issue a pull request back to this repository.
